module05/NorthwindWebApps/NorthwindApiApp/Controllers/ArticlesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Northwind.Services.Blogging;
using Northwind.Services.Employees;
using Northwind.Services.Products;

using NorthwindApiApp.ViewModels;

namespace NorthwindApiApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ArticlesController : Controller
    {
        private readonly IBloggingService bloggingService;
        private readonly IBlogCommentingService blogCommentingService;
        private readonly IEmployeeManagementService employeeManagementService;
        private readonly IProductManagementService productManagementService;

        public ArticlesController(IBloggingService bloggingService, IEmployeeManagementService employeeManagementService, IProductManagementService productManagementService, IBlogCommentingService blogCommentingService)
        {
            this.bloggingService = bloggingService;
            this.employeeManagementService = employeeManagementService;
            this.productManagementService = productManagementService;
            this.blogCommentingService = blogCommentingService;
        }

        // GET: Articles/Index
        [HttpGet]
        public ActionResult Index()
        {
            var model = bloggingService.GetBlogArticleAsync();
            return View(GetModels());

            async IAsyncEnumerable<BlogArticleViewModel> GetModels()
            {
                await foreach (var article in model)
                {
                    (_, var Employee) = await employeeManagementService.TryGetEmployeeAsync(article.EmployeeId);
                    var name = Employee?.FirstName;
                    yield return new BlogArticleViewModel()
                    {
                        BlogArticleId = article.BlogArticleId,
                        Content = article.Content,
                        EmployeeId = article.EmployeeId,
                        PublishDate = article.PublishDate,
                        Title = article.Title,
                        AuthorName = name,
                    };
                }
            }
        }

        // GET: Articles/Details/5
        [HttpGet("details/{id}")]
        public async Task<ActionResult> Details(int id)
        {
            (var flag, var article) = await bloggingService.TryGetBlogArticleAsync(id);
            if (!flag)
            {
                return this.NotFound();
            }

            (_, var Employee) = await employeeManagementService.TryGetEmployeeAsync(article.EmployeeId);
            var name = Employee?.FirstName;

            return View(new BlogArticleViewModel()
            {
                BlogArticleId = article.BlogArticleId,
                Content = article.Content,
                EmployeeId = article.EmployeeId,
                PublishDate = article.PublishDate,
                Title = article.Title,
                AuthorName = name,
            });
        }

        // GET: Articles/Create
        [HttpGet("Create")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([FromForm] ArticleFormViewModel articleForm)
        {
            if (ModelState.IsValid)
            {
                (var flag, _) = await employeeManagementService.TryGetEmployeeAsync(articleForm.EmployeeId);
                if (!flag)
                {
                    return this.BadRequest();
                }

                BlogArticle blogArticle = new BlogArticle()
                {
                    Title = articleForm.Title,
                    Content = articleForm.Content,
                    EmployeeId = articleForm.EmployeeId,
                };

                var result = await bloggingService.CreateBlogArticleAsync(blogArticle);
                if (result <= 0)
                {
                    return this.StatusCode(500);
                }

                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: Articles/Edit/5
        [HttpGet("Edit/{id}")]
        public async Task<ActionResult> Edit(int id)
        {
            (var flag, var article) = await bloggingService.TryGetBlogArticleAsync(id);
            if (!flag)
            {
                return this.NotFound();
            }

            return View(new ArticleEditFormViewModel()
            {
                Content = article.Content,
                Title = article.Title,
            });
        }

        // POST: Articles/Edit/5
        [HttpPost("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [FromForm] ArticleEditFormViewModel article)
        {
            if (ModelState.IsValid)
            {
                BlogArticle blogArticle = new BlogArticle()
                {
                    Title = article.Title,
                    Content = article.Content,
                };

                var result = await bloggingService.UpdateBlogArticleAsync(id, blogArticle);
                if (!result)
                {
                    return this.StatusCode(500);
                }

                return RedirectToAction("Index");
            }

            return View();
        }

        // POST: Articles/Delete/5
        [HttpPost("Delete/{id}")]
        public async Task<ActionResult> Delete([FromRoute] int id)
        {
            var flag = await this.bloggingService.DeleteBlogArticleAsync(id);

            if (!flag)
            {
                return this.NotFound();
            }

            return RedirectToAction("Index");
        }



        [HttpGet("details/{articleId}/products")]
        public async Task<ActionResult> RelatedProducts([FromRoute] int articleId)
        {
            (var flag, var article) = await bloggingService.TryGetBlogArticleAsync(articleId);
            if (!flag)
            {
                return this.NotFound();
            }

            List<ProductViewModel> list = new List<ProductViewModel>();
            foreach (var link in article.BlogArticleProducts)
            {
                (var exist, var product) = await productManagementService.TryGetProductAsync(link.ProductId);

                if (!exist)
                {
                    continue;
                }

                list.Add(new ProductViewModel()
                {
                    ProductId = product.ProductId,
                    ProductName = product.ProductName,
                    UnitPrice = product.UnitPrice,
                    UnitsInStock = product.UnitsInStock,
                    UnitsOnOrder = product.UnitsOnOrder,
                });
            }

            return View(new BlogArticleProductsViewModel()
            {
                BlogArticleId = article.BlogArticleId,
                Title = article.Title,
                BlogProducts = list,
            });
        }

        [HttpPost("details/{articleId}/products/create")]
        public async Task<ActionResult> CreateLinkToProduct(int articleId,[FromForm] ProductLinkViewModel productLink)
        {
            var row = await bloggingService.LinkProductToBlogArticleAsync(articleId, productLink.ProductId);

            if(row<=0)
            {
                return this.BadRequest();
            }

            return RedirectToAction("Index");
        }

        [HttpPost("details/{articleId}/products/delete")]
        public async Task<ActionResult> DeleteLinkToProduct(int articleId, [FromForm] ProductLinkViewModel productLink)
        {
            var row = await bloggingService.DeleteProductToBlogArticleLinkAsync(articleId, productLink.ProductId);

            return RedirectToAction("Index");
        }

        [HttpGet("details/{articleId}/products/edit")]
        public ActionResult EditLinkToProducts(int articleId)
        {
            ViewBag.ArticleId = articleId;
            return View();
        }



        [HttpGet("details/{articleId}/comments")]
        public async Task<ActionResult> Comments([FromRoute] int articleId)
        {
            (var flag, var article) = await bloggingService.TryGetBlogArticleAsync(articleId);
            if (!flag)
            {
                return this.NotFound();
            }

            List<BlogCommentViewModel> list = new List<BlogCommentViewModel>();
            foreach (var comment in article.BlogComments)
            {
                list.Add(new BlogCommentViewModel()
                {
                    Text = comment.Text,
                    BlogArticleId = comment.BlogArticleId,
                    CommentId = comment.CommentId,
                });
            }

            return View(new BlogArticleCommentsViewModel()
            {
                BlogArticleId = articleId,
                Title = article.Title,
                BlogComments = list,
            });
        }

        [HttpGet("details/{articleId}/comments/create")]
        public ActionResult CreateComment(int articleId)
        {
            return View();
        }

        [HttpPost("details/{articleId}/comments/create")]
        public async Task<ActionResult> CreateComment(int articleId, [FromForm] CommentFormViewModel blogComment)
        {
            if (ModelState.IsValid)
            {
                BlogComment comment = new BlogComment()
                {
                    Text = blogComment.Text,
                    BlogArticleId = articleId,
                };

                var result = await blogCommentingService.CreateBlogCommentAsync(comment);
                if (result <= 0)
                {
                    return this.BadRequest();
                }

                return RedirectToAction("Index");
            }

            return View();
        }

module05/NorthwindWebApps/NorthwindApiApp/Views/Articles/Comments.cshtml
@model BlogArticleCommentsViewModel

@{
    ViewData["Title"] = "blog comments";
}

<div>
    <h2>All comments of @Model.Title</h2>

    @foreach (var r in Model.BlogComments)
    {
        <h5>@r.CommentId</h5>
        <div>@r.Text</div>
        <div><a href="/api/articles/details/@Model.BlogArticleId/comments/edit/@r.CommentId">edit</a></div>
        <br>
    }
    <br>
    <a href="/api/articles/details/@Model.BlogArticleId/comments/create/">Leave comment</a>
</div>

module05/NorthwindWebApps/NorthwindApiApp/Views/Articles/Create.cshtml
@model ArticleFormViewModel
@{
    ViewData["Title"] = "Create article";
}

<form asp-action="Create" method="post" class="m-2">
    <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label name="Title">Title:</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Content">Content:</label>
        <input asp-for="Content" class="form-control" />
        <span asp-validation-for="Content"></span>
    </div>
    <div class="form-group">
        <label asp-for="EmployeeId">Employee id:</label>
        <input asp-for="EmployeeId" class="form-control" />
        <span asp-validation-for="EmployeeId"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create blog</button>
</form>


@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

module05/NorthwindWebApps/NorthwindApiApp/Views/Articles/CreateComment.cshtml
@model CommentFormViewModel
@{
    ViewData["Title"] = "Create article";
}

<form asp-action="CreateComment" method="post" class="m-2">
    <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label name="Text">Comment:</label>
        <input asp-for="Text" class="form-control" />
        <span asp-validation-for="Text"></span>
    </div>
    <button type="submit" class="btn btn-primary">Leave comment</button>
</form>


@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

module05/NorthwindWebApps/NorthwindApiApp/Views/Articles/Details.cshtml
@model BlogArticleViewModel

@{
    ViewData["Title"] = "List Responses";
}

<div>
    <h2>Nortwind blog by @Model.AuthorName</h2>
    <h2>@Model.Title</h2>
    <br>
    <div>@Model.Content</div>
    <br>
    <form action="/api/articles/Edit/@Model.BlogArticleId" method="get">
        <button type="submit" class="btn-link">Edit</button>
    </form>

    <form action="/api/articles/Delete/@Model.BlogArticleId" method="post">
        <button type="submit" class="btn-link">Delete</button>
    </form>

    <form action="/api/articles/details/@Model.BlogArticleId/comments/" method="Get">
        <button type="submit" class="btn-link">Comments</button>
    </form>

    <br>
    <h6>in @Model.PublishDate</h6>
</div>

module05/NorthwindWebApps/NorthwindApiApp/Views/Articles/Edit.cshtml
@model ArticleEditFormViewModel
@{
    ViewData["Title"] = "Edit article";
}

<form asp-action="Edit" method="post" class="m-2">
    <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label name="Title">Title:</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Content">Content:</label>
        <input asp-for="Content" class="form-control" />
        <span asp-validation-for="Content"></span>
    </div>
    <button type="submit" class="btn btn-primary">Edit blog</button>
</form>


@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

module05/NorthwindWebApps/NorthwindApiApp/Views/Articles/EditComment.cshtml
@model CommentFormViewModel
@{
    ViewData["Title"] = "Edit article";
}

<form asp-action="CreateComment" method="post" class="m-2">
    <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label name="Text">Comment:</label>
        <input asp-for="Text" class="form-control" />
        <span asp-validation-for="Text"></span>
    </div>
    <button type="submit" class="btn btn-primary">Leave comment</button>
</form>


@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

module05/NorthwindWebApps/NorthwindApiApp/Views/Articles/EditLinkToProducts.cshtml
@model ProductLinkViewModel

@{
    ViewData["Title"] = "List Responses";
}

<div>
    <h2>Add or delete products from @ViewBag.ArticleId blog</h2>
    <br>
    <form action="/api/articles/details/@ViewBag.ArticleId/products/create" method="post">
        <div class="form-group">
            <label name="ProductId">Product Id:</label>
            <input asp-for="ProductId" class="form-control" />
            <span asp-validation-for="ProductId"></span>
        </div>
        <button type="submit" class="btn-link">Add</button>
    </form>

    <form action="/api/articles/details/@ViewBag.ArticleId/products/delete" method="post">
        <div class="form-group">
            <label name="ProductId">Product Id:</label>
            <input asp-for="ProductId" class="form-control" />
            <span asp-validation-for="ProductId"></span>
        </div>
        <button type="submit" class="btn-link">Delete</button>
    </form>
</div>

module05/NorthwindWebApps/NorthwindApiApp/Views/Articles/Index.cshtml
@model IAsyncEnumerable<BlogArticleViewModel>

@{
    ViewData["Title"] = "List Responses";
}

<div>
    <h2 >All northwind blogs</h2>
    <table>
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Title
            </th>
            <th>
                Posted
            </th>
            <th>
                Author Id
            </th>
            <th>
                Author Name
            </th>
        </tr>
    </thead>
    <tbody>
        @await foreach (var r in Model)
        {
        <tr>
            <td>@r.BlogArticleId</td>
            <td><a href="/api/articles/Details/@r.BlogArticleId">@r.Title</a></td>
            <td>@r.PublishDate</td>
            <td>@r.EmployeeId</td>
            <td>@r.AuthorName</td>
            <td><a href ="/api/articles/details/@r.BlogArticleId/products">Related products</a></td>
        </tr>
        }
    </tbody>
    </table>
    <br>
    <a asp-controller="Articles" asp-action="Create">Add+</a>
</div>

module05/NorthwindWebApps/NorthwindApiApp/Views/Articles/RelatedProducts.cshtml
@model BlogArticleProductsViewModel

@{
    ViewData["Title"] = "List Responses";
}

<div>
    <h2>All products of @Model.Title</h2>
    <table>
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Unit Price
                </th>
                <th>
                    Units In Stock
                </th>
                <th>
                    Units On Order
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var r in Model.BlogProducts)
            {
                <tr>
                    <td>@r.ProductId</td>
                    <td>@r.ProductName</td>
                    <td>@r.UnitPrice</td>
                    <td>@r.UnitsInStock</td>
                    <td>@r.UnitsOnOrder</td>
                </tr>
            }
        </tbody>
    </table>
    <br>
    <a href ="/api/articles/details/@Model.BlogArticleId/products/edit">Edit</a>
</div>